version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.diffplug.spotless
        versions:
          - ">6.13.0"
