version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.diffplug.spotless
        # spotless 6.14.0+ requires Java 11
        versions: ["[6.13.0,)"]
