# Starter build/test workflow.  We will continue to enhance.
name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu
        java: 17
        distribution: temurin
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Test and build Jar
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: jar

  test:
    name: test-java-version-${{ matrix.test-java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Add distributions to matrix
        test-java-version:
          - 8
          - 11
          - 17
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - id: setup-test-java
        name: Set up JDK ${{ matrix.test-java-version }}-${{ matrix.vm }} for running tests
        uses: actions/setup-java@v3
        with:
          # using zulu because new releases get published quickly
          distribution: temurin
          java-version: ${{ matrix.test-java-version }}

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          # spotless is checked separately since it's a common source of failure
          arguments: test